services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    ports:
      - "127.0.0.1:9080:9080"  # Added localhost binding for security
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s  # Added start period
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - NODE_ENV=production
    volumes:
      - backend-logs:/app/logs

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      backend:
        condition: service_healthy  # Added health check dependency
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s  # Added start period
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./frontend/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro  # Fixed config file name
      - frontend-assets:/usr/share/nginx/html

volumes:
  backend-logs:
    driver: local
  frontend-assets:
    driver: local

networks:
  app-network:
    driver: bridge