version: '3.8'
services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - build_volume:/app/build
    ports:
      - "9080:9080"
    command: sh -c "mkdir -p /app/build && cd /app/build && cmake .. && make && ./server"

volumes:
  build_volume: